# Generated by Django 5.0.6 on 2024-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Macro_Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("code_snippet", models.TextField()),
                ("code_file", models.FileField(upload_to="code_snippets/")),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="project_videos/"
                    ),
                ),
            ],
        ),
    ]
