# Generated by Django 5.0.6 on 2024-05-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="macro_project",
            name="code_file",
        ),
    ]
