# Generated by Django 5.0.6 on 2024-05-23 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_macro_project_code_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="macro_project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
