# Generated by Django 5.0.6 on 2024-05-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_macro_project_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macro_project",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="macro_project",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
