# Generated by Django 5.0.6 on 2024-05-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_macro_project_options_macro_project_my_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macro_project",
            options={},
        ),
        migrations.RemoveField(
            model_name="macro_project",
            name="my_order",
        ),
    ]
