# Generated by Django 5.0.6 on 2024-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_macro_project_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macro_project",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="macro_project",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
