# Generated by Django 5.0.6 on 2024-05-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_macro_project_macroscript_project"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Macroscript_Project",
            new_name="Macro_Project",
        ),
    ]
