# Generated by Django 5.0.6 on 2024-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_script_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="macro_project",
            name="disclaimer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="script_project",
            name="disclaimer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
