# Generated by Django 5.0.6 on 2024-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_macro_project_disclaimer_script_project_disclaimer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Website_Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("link", models.TextField()),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="project_videos/"
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True, null=True, upload_to="project_screenshots/"
                    ),
                ),
                ("disclaimer", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
