# Generated by Django 5.0.6 on 2024-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_contact_siteconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
