# Generated by Django 5.0.6 on 2024-05-26 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_pagevisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pagevisit",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
