# Generated by Django 5.0.6 on 2024-05-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_session_delete_pagevisit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
