# Generated by Django 5.0.6 on 2024-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_delete_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("visit_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
